### ISSUE TITLE
.DS_Store in node_modules

### ISSUE THREAD

**Issue by stahlmanDesign** [jprichardson/fix-dropbox-node_modules-symlinks#1]
On a Mac, if you look inside the node_modules folder, the OS creates a **.DS_Store** file to save the position of icons or view preferences side sort by date or alphabetical. The presence of this file breaks your tool. Can you set it to ignore **.DS_Store**? (If I erase **.DS_Store** and run `fix-dropbox-node_modules-symlinks --overwrite` it works, but the OS quickly creates a new **.DS_Store** file

**Comment by jprichardson** [comment]
Sure, would you be willing to submit a pull request?

**Comment by jprichardson** [comment]
Closed with https://github.com/jprichardson/fix-dropbox-node_modules-symlinks/pull/2
