### ISSUE TITLE
After overriding files still found as symlink?

### ISSUE THREAD

**Issue by bhuisman1992** [jprichardson/fix-dropbox-node_modules-symlinks#3]
Hi there,

After i run the script the symlink files are still recognized as symlink files when i run: find ~/Dropbox -type l -exec ls -lah {} \;

Is this normal? The script logs that it's done:

fix-dropbox-node_modules-symlinks --overwrite

  ../atob/bin/atob.js => node_modules/.bin/atob
  ../color-support/bin.js => node_modules/.bin/color-support
  ../gulp/bin/gulp.js => node_modules/.bin/gulp
  ../mkdirp/bin/cmd.js => node_modules/.bin/mkdirp
  ../semver/bin/semver => node_modules/.bin/semver
  ../strip-bom/cli.js => node_modules/.bin/strip-bom
  ../user-home/cli.js => node_modules/.bin/user-home
  ../which/bin/which => node_modules/.bin/which

  done.

Many thx!

**Comment by jprichardson** [comment]
I don't understand the question. The intention of this script is to overwrite Dropbox's behavior of replacing valid symlinks with the file itself i.e. this script recreates the symlinks.
